---
version: 2
plan:
  project-key: WEBCO
  key: HEMA
  name: static-http-error-pages

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Release:
      manual: true
      jobs:
        - Release

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/usr/bin/env bash
        set -e
        /opt/scripts/git/git-repository-information-restore.sh
        docker run -e http_proxy=${bamboo.http_proxy} -e https_proxy=${bamboo.http_proxy} -e HTTP_PROXY=${bamboo.http_proxy} -e HTTPS_PROXY=${bamboo.http_proxy} -e GIT_REPO=${bamboo_repository_git_repositoryUrl} -e RELEASE_VERSION=${bamboo.release_version} acd-docker.repository.milieuinfo.be/milieuinfo/wc-release:1.0.0
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: WEBCO-HEMA

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin

